/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT evmAudioTemplate.cdb */

/*  Include Header Files  */
#include <std.h>
#include <hst.h>
#include <swi.h>
#include <tsk.h>
#include <log.h>
#include <sem.h>
#include <sts.h>

#ifdef __cplusplus
extern "C" {
#endif

extern far HST_Obj RTA_fromHost;
extern far HST_Obj RTA_toHost;
extern far SWI_Obj KNL_swi;
extern far TSK_Obj TSK_idle;
extern far TSK_Obj TSK_AUDIO;
extern far TSK_Obj TSK_ALIVE;
extern far TSK_Obj TSK_SETDELAY;
extern far TSK_Obj TSK_SETMODE;
extern far LOG_Obj LOG_system;
extern far LOG_Obj trace;
extern far SEM_Obj semRx;
extern far SEM_Obj semTx;
extern far STS_Obj IDL_busyObj;


#ifdef __cplusplus
}
#endif /* extern "C" */
